name: 'Syncronize pull_request and redmine issue'
description: 'プルリクエストとRedmineチケットを連携します。'
author: 'mana544'
inputs:
  gh-token:
    description: 'Specify the token to edit to pull_request.'
    required: false
    default: ${{ github.token }}
  rm-host:
    description: 'Redmine host URL'
    required: true
    default: 'http://127.0.0.1:3000/'
  rm-api-key:
    description: 'Redmine API Key'
    required: true
    default: ''
  marker-pr-url-in-rm:
    description: 'Redmine チケットの説明欄に埋め込む、pull_request URLに置換するマーカー文字列'
    required: false
    default: '@INSERT_PR_URL@'
  marker-rm-url-in-pr:
    description: 'pull_request descriptionに埋め込む、RedmineチケットURLに置換するマーカー文字列'
    required: false
    default: '`INSERT_RM_URL`'
  issue-num-regexp-pattern:
    description: 'ブランチ名からチケット番号を抽出するための正規表現パターン'
    required: false
    default: '[0-9]+$'
  sts-id-if-opened-pr:
    description: 'プルリクエストopened のときの、Redmineチケットのstatus_id'
    required: false
    default: 1
  sts-id-if-reopened-pr:
    description: 'プルリクエストreopened のときの、Redmineチケットのstatus_id'
    required: false
    default: 2
  sts-id-if-mergeclosed-pr:
    description: 'プルリクエストclosed(merge) のときの、Redmineチケットのstatus_id'
    required: false
    default: 3
  sts-id-if-unmergeclosed-pr:
    description: 'プルリクエストclosed(unmerged) のときの、Redmineチケットのstatus_id'
    required: false
    default: 4
  
runs:
  using: 'node16'
  main: 'index.js'